CREATE SEQUENCE dbo.USER_SEQ as int 
    START WITH 1
    INCREMENT BY 1
go

CREATE SEQUENCE dbo.CLIENT_SEQ as int 
    START WITH 1
    INCREMENT BY 1
go

CREATE SEQUENCE dbo.PERSON_SEQ as int 
    START WITH 1
    INCREMENT BY 1
go

CREATE SEQUENCE dbo.MODEL_SEQ as int 
    START WITH 1
    INCREMENT BY 1
go

CREATE SEQUENCE dbo.DETAIL_SEQ as bigint 
    START WITH 1
    INCREMENT BY 1
go

CREATE SEQUENCE dbo.MACHINERY_SEQ as int 
    START WITH 1
    INCREMENT BY 1
go

CREATE SEQUENCE dbo.MACHINERY_CLIENT_SEQ as int 
    START WITH 1
    INCREMENT BY 1
go