server:
  port : 8081

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        cache:
          use_query_cache: false
          use_second_level_cache: true
        format_sql: true
        use_sql_comments: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pdd-test
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 20
      transaction-isolation: TRANSACTION_READ_COMMITTED
      connection-test-query: SELECT current_timestamp
      read-only: false

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"